table themes
	lineageTag: de7a4969-ccae-4c0f-88e2-e77b0b35e438

	column id
		dataType: int64
		formatString: 0
		lineageTag: f290eabd-6b14-4153-a395-beb790d1d560
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: f679d873-47e5-45b7-881f-4b7d711b7cb5
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column parent_id
		dataType: int64
		formatString: 0
		lineageTag: 1a528e8a-8d5a-460c-9575-ce3e729d96fb
		summarizeBy: none
		sourceColumn: parent_id

		annotation SummarizationSetBy = Automatic

	partition themes = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Acer\davi\legostarwarspowerbi-main\data\themes.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"name", type text}, {"parent_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

